### ISSUE TITLE
Feature: tie repeat posts about a link to the same thread

### ISSUE THREAD

**Issue by 33mhz** [dasdom/phazel#1]
This could work a couple of ways. The primary intent would be to tie together posts about the same article from the same person. So phazel could have a list of links it has posted to from the user on the phone, and when you post, it would check if you're sharing the same link again. If so, it would either automatically, or maybe conditionally, or maybe based on a preference automatically, make the new post a reply to the old post.

You'd probably flush links older than 48hrs or some such.

Make sense?

Good example is how @jeremy-w uses it; posting a few times about the same article.

**Comment by dasdom** [comment]
Good idea. Will come!

**Comment by dasdom** [comment]
The last url that was posted is stored. And when the user tries to share the link again, the new post is added to the same thread.
